---
kind: pipeline
name: Apply templates

steps:
- name: slack
  image: plugins/slack
  settings:
    webhook:
      from_secret: SLACK_WEB_URL
    channel: document-code
  when:
    status: [ success, failure ]
